apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:
    - image: farberg/popular-slides
      context: web-app

    - image: farberg/popular-slides-spark
      context: spark-app

    - image: schaeufler/impfpass-frontend
      context: impfpass-frontend

    - image: schaeufler/impfpass-backend
      context: impfpass-backend

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
