apiVersion: apps/v1
kind: Deployment
metadata:
  name: impfpassbackend-deployment
  labels:
    app: impfpassbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impfpassbackend
  template:
    metadata:
      labels:
        app: impfpassbackend
    spec:
      containers:
        - name: impfpassbackend
          image: schaeufler/impfpass-backend
          ports:
            - containerPort: 3000
#          envFrom:
#            - configMapRef:
#                name: impfpassapp-configmap
          env:
            # Definition of Env-Vars
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: impfpassapp-configmap
                  key: PORT
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: impfpassapp-configmap
                  key: APP_ENV
        volumeMounts:
          - name: config
            #specify folder
            mountPath: "/"
            readOnly: true
      volumes:
        # See: https://kubernetes.io/docs/concepts/configuration/configmap/
        - name: config
          configMap:
            name: impfpassapp-configmap
            # The Keys from the Config-Map to create a file of
            items:
              - key: "db.env"
                path: "db.env"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: impfpassapp-configmap
data:
  PORT: 3000
  APP_ENV: production
  db.env: |
    DB_HOST=impfpassdb-service
    DB_NAME=vacbook
    DB_PORT=3306
    DB_WAITFORCONNECTIONS=true
    DB_CONNECTION_LIMIT=10
    DB_QUEUE_LIMIT=0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: impfpassfrontend-deployment
  labels:
    app: impfpassfrontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: impfpassfrontend
  template:
    metadata:
      labels:
        app: impfpassfrontend
    spec:
      containers:
        - name: impfpassfrontend
          image: schaeufler/impfpass-frontend
          ports:
            - containerPort: 3000
---
#Impfpass Backend Service
# see for further details: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: impfpass-backend-service
spec:
  selector:
    app: impfpassbackend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
#Impfpass Frontend Service
# see for further details: https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: impfpass-frontend-service
spec:
  selector:
    app: impfpassfrontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
#Ingress for frontend and backend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: impfpass-ingress
# no need for rewrite
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: impfpass-frontend-service
                port:
                  number: 3000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: impfpass-backend-service
                port:
                  number: 3000